#! /bin/sh

## NOTE: So far, this script has worked with Gmail and Yahoo Mail.

## Variables
option="$1"
account="$2"

## Functions
error() {
	printf "%s\n" "$1" &&
	exit 1
}

plshelp() {
	echo "
mutt-x — deploys x1nigo's configuration file(s) for neomutt as an email client.
Usage:
	mx [OPTION] [username@email.com]
Options:
	a <your@email.com>	Add user email.

	d 	Delete user.

	o 	Opens neomutt with specified email.

	s  	Syncs mail and downloads them to your mail directory
		for offline usage.

	l	Lists all accounts of mutt-x.
	
	h 	Displays this help text.
"
}

syncuser() {
	emailaccount=$(ls $HOME/.config/mutt/accounts | sed 's/.muttrc//' | dmenu -p "Select email account:" -l 5)
	[ -z $emailaccount ] && error "No email input! Try again."
	email=$(echo $emailaccount | sed 's/^.*@\(.*\.\).*$/\1/' | sed 's/\..*//')
	[ "$email" = "yahoo" ] && email="mail.yahoo"

	mbsync -c $HOME/.config/isync/accounts/$emailaccount.mbsyncrc $email 2>/dev/null &&

	newmail=$(ls $HOME/.mail/$email/Inbox/new | wc -l)
	if [[ $newmail -gt 0 ]]; then
		notify-send -t 5000 "📧 You have ($newmail) new mail!"
	fi
}

deleteuser() {
	emailaccount=$(ls $HOME/.config/mutt/accounts | sed 's/.muttrc//' | dmenu -p "Select email account:" -l 5)
	[ -z $emailaccount ] && error "No email input! Try again."

	sudo rm $HOME/.config/mutt/accounts/$emailaccount.muttrc
	sudo rm $HOME/.config/isync/accounts/$emailaccount.mbsyncrc
}

mbsyncinstall() {
	echo "
IMAPAccount $email
Host imap.$email.com
User $account
PassCmd \"pass show $account\"
SSLType IMAPS
CertificateFile /etc/ssl/certs/ca-certificates.crt

IMAPStore $email-remote
Account $email

MaildirStore $email-local
SubFolders Verbatim
Path ~/.mail/$email/
Inbox ~/.mail/$email/Inbox

Channel $email
Far :$email-remote:
Near :$email-local:
Patterns *
Create Both
Expunge Both
SyncState *
" > $HOME/.config/isync/accounts/$account.mbsyncrc
}

muttinstall() {
	echo "
set imap_user = \"$account\"
set smtp_pass = \"\`pass show $account\`\"
set folder = \"~/.mail/$email/\"
set smtp_url = \"smtp://$account@smtp.$email.com:587/\"
set from = \"$account\"

set spoolfile = \"+Inbox\"
set record = \"+Sent\"
set trash = \"+Trash\"
$unsetrecord
$draftfolder

$mailboxes

set sidebar_visible = yes
set sidebar_format = \"%B%?F? [%F]?%* %?N?%N/?%S\"
set sidebar_width = 20
set sidebar_short_path = yes
set sidebar_delim_chars = '/.'
set mail_check_stats
set editor = vim
set index_format = \"%4C %Z %{!%d %b %Y} %-20.20Fp %s %c\"

set sort = reverse-date-received

## Bindings
bind index,pager \Ck sidebar-prev
bind index,pager \Cj sidebar-next
bind index,pager \Co sidebar-open
bind index,pager \Cb sidebar-toggle-visible
bind index,pager,attach h exit
bind index l display-message
bind pager l view-attachments
bind attach l view-attach

## Basics
color normal white default
color indicator brightblack white
color tree yellow default
color status brightwhite black
color error red default
color message color253 default
color signature brightred default
color attachment cyan default
color search color100 default
color tilde color130 default
color markers color138 default
color hdrdefault brightblue default

color quoted red default
color quoted1 red default
color quoted2 red default
color quoted3 red default
color quoted4 red default
color quoted5 red default
color quoted6 red default
color quoted7 red default
color quoted8 red default
color quoted9 red default

## Index
color index brightdefault black '(~N|~O)'
color index_author red default '.*'
color index_date yellow default
color index_number blue default
color index_subject blue default '.*'
color index_size cyan default
color index_flags brightred default '(~D|~r)'

## Pager
color header brightblue default '^date:'
color header brightblue default '^(to|cc|bcc):'
color header brightblue default '^from:'
color header brightblue default '^subject:'
color header brightblue default '^user-agent:'
color header brightblue default '^reply-to:'
color header brightblue default '^x-mailer:'
color body white default '.*'
color body brightred default '((fttp|http|https)://|news:)[^ >)\"\t]+'

## Sidebar
color sidebar_divider black black
color sidebar_highlight brightwhite black
color sidebar_indicator brightblack white
color sidebar_new brightgreen default
color sidebar_ordinary white default
color sidebar_unread brightcyan default
" > $HOME/.config/mutt/accounts/$account.muttrc
}

adduser() {
	[ -z $account ] && error "No email input! Try again."

	if [ $(ls $HOME/.config/mutt/accounts/$account*) ]; then
		error "Email already exists! Try another one."
	fi

	email=$(echo $account | sed 's/^.*@\(.*\.\).*$/\1/' | sed 's/\..*//')
	[ "$email" = "yahoo" ] && email="mail.yahoo"

	if [ "$email" = "gmail" ]; then
		unsetrecord="unset record"
		draftfolder="set postponed = \"+[Gmail]/Drafts\""
		mailboxes="mailboxes =Inbox =\"[Gmail]/Sent Mail\" =[Gmail]/Important =[Gmail]/Starred =[Gmail]/Drafts =[Gmail]/Spam =Trash"
	elif [ "$email" = "mail.yahoo" ]; then
		unsetrecord=""
		draftfolder="set postponed = \"+Draft\""
		mailboxes="mailboxes =Inbox =Sent =Draft =Trash"
	else
		unsetrecord=""
		draftfolder="set postponed = \"+Drafts\""
		mailboxes="mailboxes =Inbox =Sent =Drafts =Trash"
	fi

	pass add $account

	mkdir -p $HOME/.mail/$email/

	muttinstall || error "There was an error setting up muttrc for your email."
	mbsyncinstall || error "Failed to set up an mbsyncrc file for your email."
}

openmail() {
	emailaccount=$(ls $HOME/.config/mutt/accounts | sed 's/.muttrc//' | dmenu -p "Select email account:" -l 5)
	[ -z $emailaccount ] && error "No email input! Try again."

	echo "
source $HOME/.config/mutt/accounts/$emailaccount.muttrc
" > $HOME/.config/mutt/muttrc

	neomutt 2>/dev/null && echo "" > $HOME/.config/mutt/muttrc
}

listusers() {
	ls $HOME/.config/mutt/accounts | cat -n | sed 's/.muttrc//'
}

case "$option" in
	a) adduser ;;
	d) deleteuser ;;
	s) syncuser ;;
	o) openmail ;;
	h) plshelp ;;
	l) listusers ;;
	*) plshelp ;;
esac
